### ISSUE TITLE
installation error messages (version incompatibility)

### ISSUE THREAD

**Issue by yaceben** [ThreeSixtyGiving/datatester#39]
Hi,

When I try to install as per the specified instructions in a conda env it will give me the following errors:
```bash
ERROR: cove 0.0.0 has requirement Django==1.11.11, but you'll have django 1.11.15 which is incompatible.
ERROR: cove 0.0.0 has requirement openpyxl==2.5.1, but you'll have openpyxl 2.5.5 which is incompatible.
```
A simple fix would be to downgrade version specified in requirements.txt ?

Cheers

**Comment by Bjwebb** [comment]
Thanks for taking the time to report this. Sorry, that this has remained an issue, because no-one on our team uses conda.

Becuase the older version of Django has security issues, I think we should update the [cove commit](https://github.com/ThreeSixtyGiving/datatester/blob/master/requirements.in#L2) that we use. @michaelwood could you take a look at this as part of your current datastore work?

**Comment by michaelwood** [comment]
I've recently[1] reorganised the dependencies which may help with this. So far those version error conflicts haven't caused any regressions and with pip based installation you can safely ignore them. [1] https://github.com/ThreeSixtyGiving/datatester/commit/acc5ab7d4293838c2ba67c1f86eb3bae4c969dd7

**Comment by Bjwebb** [comment]
Thanks @michaelwood.

I've tested `master` in a conda env, and it works now.
